apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-scaler
  template:
    metadata:
      labels:
        app: deployment-scaler
    spec:
      serviceAccountName: deployment-scaler-sa
      containers:
      - name: deployment-scaler
        image: gcr.io/ea-k8s-381622/k8s-deployment-scaler:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: kubeconfig
          mountPath: "/kubeconfig"
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig

---

apiVersion: v1
kind: Service
metadata:
  name: deployment-scaler
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: deployment-scaler

