apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-scaler-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-scaler-role
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "deployments/scale", "pods", "pods/log"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-scaler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployment-scaler-role
subjects:
- kind: ServiceAccount
  name: deployment-scaler-sa
  namespace: default

